import json
import pandas as pd
import glob

def process_file(file):
    with open(file) as f:
        data = json.load(f)
    
    return {
        "city": data["name"],
        "temperature": data["main"]["temp"],
        "humidity": data["main"]["humidity"],
        "wind_speed": data["wind"]["speed"],
        "timestamp": data["dt"]
    }

def main():
    files = glob.glob("data/*.json")
    
    records = [process_file(f) for f in files]
    
    df = pd.DataFrame(records)
    df.to_csv("data/processed_weather.csv", index=False)
    
    print("Processed data saved!")

if __name__ == "__main__":
    main()

# Weather Data Transformation Script
#
# This script processes raw weather JSON files and converts
# them into a structured CSV dataset for analysis and storage.
#
# Main steps:
# 1. Read raw JSON weather files from the Data/ directory
# 2. Extract relevant weather attributes from each file
# 3. Convert the extracted records into a pandas DataFrame
# 4. Save the cleaned and structured data as a CSV file
#
# Extracted fields:
# city, temperature, humidity, wind_speed, timestamp
#
# Input:
# Raw JSON files generated by the weather fetching script
#
# Output:
# Data/processed_weather.csv
#
# The script enables transformation of unstructured API
# responses into a tabular format suitable for databases
# and analytics workflows.
